.TH KIGEN "8" "June 2010" "kigen 0.1.5" "Gentoo Linux"
.SH NAME
kgen \- a GNU/Linux kernel|initramfs generator.
.SH SYNOPSIS
\fBkgen\fR \fI<options>\fR
.SH INTRODUCTION
KIGen is designed to allow users to build their own kernel/initramfs
provided adequate configuration and parameters.
KIGen provides:
  - kgen: a kernel build interface
  - igen: an initramfs build interface
.PP
kgen so far provides the following features:
  - kernel build
    - bzImage
    - modules
.SH USAGE
You can add any appropriate options to customize its behavior.
The most commonly used syntax would be:
.PP
# kgen --clean --dotconfig=/file --menuconfig
.PP
This would successively prepare/compile the kernel, compile/install its modules.
Note that the resulting output is appended into /boot, it is up to the user
to ensure /boot is correctly mounted.
.SH OPTIONS
kgen supports the following options.
.TP
\fB\-h, \-\-help
Help menu.
.TP
\fB\-\-config=\fR/file
Provide a custom master config file in case none exists as /etc/kigen.conf.
.TP
\fB\-n, \-\-nocolor
Remove color ouput feature.
.TP
\fB\-d, \-\-debug
Debug.
.TP
\fB\-\-dotconfig=\fR/foo/bar/.config
Provide a customized .config file for the kernel.
.TP
\fB\-\-rename=\fR<kernelname>
Customize kernel name
.TP
\fB\-\-initramfs=\fR/file
Will add an initramfs compiled into the kernel itself.
You can use igen to create an initramfs and then feed it back to kgen.
.TP
\fB\-\-fixdotconfig
Will attempt to fix kernel .config options. Supported:
 - CONFIG_INITRAMFS_SOURCE for --initramfs=/file --fixdotconfig
.TP
\fB\-\-mrproper
Clean precompiled objects and configuration.
.TP
\fB\-\-clean
Clean precompiled objects.
.TP
\fB\-\-oldconfig
Will ask for new kernel options.
.TP
\fB\-\-nooldconfig
Will not ask for new kernel options.
.TP
\fB\-\-menuconfig
Interactive kernel/initramfs options menu.
.TP
\fB\-\-nomodinstall
Do not install kernel modules
.TP
\fB\-\-nosaveconfig
Do not save kernel config
.TP
\fB\-\-fakeroot=\fR</dir>
Use a fake root dir to install kernel modules
.TP
\fB\-\-noboot
Do not copy kernel/initramfs to /boot.
.TP
\fB\-\-logfile=/file
Log to file.
./TP
\fB\-\-version
Display program version.
.TP
.RE
.SH AUTHORS
.nf
erick 'r1k0' michau <erick@openchill.org>
.fi
