.TH KIGEN "8" "September 2010" "kigen 0.2.1" "Gentoo Linux"
.SH NAME
kigen \- a GNU/Linux kernel|initramfs generator.
.SH SYNOPSIS
\fBkigen\fR \fI<options|target>\fR \fI[parameters]
.SH DESCRIPTION
KIGen is designed to allow users to build custom kernels and initramfs.
It is split into 2 main targets:
 - kernel
 - initramfs

The 'kernel' target accesses the kernel build features and 
the 'initramfs' provides from scratch and sources boot features.

KIGen supports other distributions by the mean of 
the --linuxrc=/linuxrc[,/file] option but the engine has yet 
some Portage assumptions (which will slowly be replaced across
the 0.2.* cycle).
.PP
.SH MAIN OPTIONS
kigen supports the following options.
.TP
\fB\-h, \-\-help
Help menu and examples.
.TP
\fB\-n, \-\-nocolor
Remove color ouput feature.
.TP
\fB\-\-version
Display program version.
.TP
\fB\-\-credits
Display credits and license.

.PP
.SH 'kernel' PARAMETERS
.TP
\fB\-d, \-\-debug
Debug.
.TP
\fB\-\-dotconfig=\fR/foo/bar/.config
Provide a customized .config file for the kernel.
.TP
\fB\-\-rename=\fR<kernelname>
Customize kernel name
.TP
\fB\-\-initramfs=\fR/file
Will add an initramfs compiled into the kernel itself.
You can use igen to create an initramfs and then feed it back to kigen.
.TP
\fB\-\-fixdotconfig
Will attempt to fix kernel .config options. Supported:
 - CONFIG_INITRAMFS_SOURCE for --initramfs=/file --fixdotconfig
.TP
\fB\-\-mrproper
Clean precompiled objects and configuration.
.TP
\fB\-\-clean
Clean precompiled objects.
.TP
\fB\-\-oldconfig
Will ask for new kernel options.
.TP
\fB\-\-nooldconfig
Will not ask for new kernel options.
.TP
\fB\-\-menuconfig
Interactive kernel/initramfs options menu.
.TP
\fB\-\-nomodinstall
Do not install kernel modules
.TP
\fB\-\-nosaveconfig
Do not save kernel config
.TP
\fB\-\-fakeroot=\fR</dir>
Use a fake root dir to install kernel modules
.TP
\fB\-\-noboot
Do not copy kernel/initramfs to /boot.
.TP
\fB\-\-logfile=/file
Log to file.

.PP
.SH 'initramfs' PARAMETERS
.TP

.PP
.SH EXAMPLES
# kigen etc
.PP

.PP
.SH AUTHORS
erick 'r1k0' michau <erick@openchill.org>
.PP
