.TH KIGEN "8" "June 2011" "kigen 0.3.1" "Gentoo Linux"
.SH NAME
kigen \- a GNU/Linux kernel|initramfs generator for Portage.
.SH SYNOPSIS
\fBkigen\fR \fI<options|target>\fR \fI[parameters]
.SH DESCRIPTION
KIGen is designed to allow users to build custom kernels and initramfs.
It is split into 3 main targets:
 - kernel
 - initramfs
 - tool

The 'kernel' target accesses the kernel build features and 
the 'initramfs' provides from scratch and sources boot features.
The 'tool' target is there to provide handy tools related to kernel/initramfs.

KIGen supports other distributions by the mean of 
the --linuxrc=/linuxrc[,/file] option but the engine has yet 
some Portage assumptions (which will slowly be replaced across
the 0.3.* cycle).
.PP
.SH MAIN OPTIONS
kigen supports the following options.
.TP
\fB\-h, \-\-help
Help menu and examples.
.TP
\fB\-n, \-\-nocolor
Remove color ouput feature.
.TP
\fB\-\-version
Display program version.
.TP
\fB\-\-credits
Display credits and license.

.PP
.SH 'kernel' PARAMETERS
.TP

\fB\-\-dotconfig=\fR/file
Custom kernel .config file
.TP
\fB\-\-initramfs=\fR/file
Embed initramfs into the kernel
.TP
  \fB\-\-fixdotconfig
  Check and auto fix the kernel config file (experimental)
.TP
\fB\-\-clean
Clean precompiled objects only
.TP
\fB\-\-mrproper
Clean precompiled objects and remove config file
.TP
\fB\-\-oldconfig
Ask for new kernel options if any
.TP
\fB\-\-menuconfig
Interactive kernel options menu
.TP
\fB\-\-fakeroot=\fR/dir
Append modules to /dir/lib/modules
.TP
\fB\-\-nooldconfig
Do not ask for new kernel/initramfs options
.TP
\fB\-\-nomodinstall
Do not install modules
.TP
\fB\-\-nomodules
Do not compile or install modules
.TP
\fB\-\-nosaveconfig
Do not save kernel config in /etc/kernels
.TP
\fB\-\-noboot
Do not copy kernel to /boot
.TP
\fB\-\-rename=\fR/file
Custom kernel file name
.TP
\fB\-\-logfile=\fR/file
Log to file
.TP
\fB\-\-debug, \fB\-d
Debug verbose

.PP
.SH 'initramfs' PARAMETERS
.TP

\fB\-\-linuxrc=\fRlinuxrc[,/file]
Include custom linuxrc (files copied over to etc)
.TP
\fB\-\-dotconfig=\fR/file
Custom busybox .config file
.TP
\fB\-\-defconfig
Set .config to largest generic options
.TP
\fB\-\-oldconfig
Ask for new busybox options if any
.TP
\fB\-\-menuconfig
Interactive busybox options menu
.TP
\fB\-\-splash=\fR<theme>
Include splash support (splashutils must be merged)
.TP
  \fB\-\-sres=\fR[YxZ[,YxZ]
  Splash resolution, all if not set
.TP
\fB\-\-bin-disklabel, \fB\-\-source-disklabel
Include support for UUID/LABEL from host or sources
.TP
\fB\-\-bin-luks, \fB\-\-source-luks
Include LUKS support from host or sources
.TP
\fB\-\-bin-dmraid, \fB\-\-source-dmraid
Include DMRAID support from host or sources
.TP
\fB\-\-bin-evms
Include EVMS support from host
.TP
\fB\-\-bin-lvm2, \fB\-\-source-lvm2
Include LVM2 support from host or sources
.TP
\fB\-\-bin-dropbear, \fB\-\-source-dropbear
Include dropbear tools and daemon from host or sources
.TP
  \fB\-\-debugflag
  Compile dropbear with #define DEBUG_TRACE in debug.h
.TP
\fB\-\-rootpasswd=\fR<passwd>
Create and set root password (required for dropbear)
.TP
\fB\-\-keymaps
Include all keymaps
.TP
\fB\-\-ttyecho
Include the handy ttyecho.c tool
.TP
\fB\-\-bin-strace, \fB\-\-source-strace
Include the strace binary tool from host or sources
.TP
\fB\-\-plugin=\fR/dir[,/dir]
Include list of user generated custom roots
.TP
\fB\-\-bin-glibc
Include host GNU C libraries from host (required for DNS,dropbear)
.TP
\fB\-\-bin-libncurses
Include host libncurses from host (required for dropbear)
.TP
\fB\-\-bin-zlib
Include host zlib from host (required for dropbear)
.TP
\fB\-\-nocache
Do not use cached data
.TP
\fB\-\-hostbin
Use host binaries over sources when possible
.TP
\fB\-\-noboot
Do not copy initramfs to /boot
.TP
\fB\-\-rename=\fR/file
Custom initramfs file name
.TP
\fB\-\-logfile=\fR/file
Log to file
.TP
\fB\-\-debug, \fB\-d
Debug verbose

.PP
.SH 'tool' PARAMETERS
.TP

\fB\-\-getdotconfig=\fR/vmlinux
Extract .config from compiled binary kernel (if IKCONFIG has been set)

\fB\-\-extract=\fR/file
Extract initramfs file
.TP
  \fB\-\-to=\fR/dir
  Custom extracting directory
.TP
\fB\-\-compress=\fR/dir
Compress directory into initramfs
.TP
  \fB\-\-into=\fR/file
  Custom initramfs file

.PP
.SH AUTHORS
erick 'r1k0' michau <erick@openchill.org>
.PP
